//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Categories = new HashSet<Category>();
            this.VehicleBrands = new HashSet<VehicleBrand>();
            this.VehicleModels = new HashSet<VehicleModel>();
        }
    
        public string Username { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<VehicleBrand> VehicleBrands { get; set; }
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
    }
}
