//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int CartItemId { get; set; }
        public decimal ItemUnitPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> ShoppingCartID { get; set; }
        public Nullable<int> SpareId { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual Spare Spare { get; set; }
    }
}
