//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public Retailer()
        {
            this.Spares = new HashSet<Spare>();
        }
    
        public string Username { get; set; }
        public string Address { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Spare> Spares { get; set; }
    }
}
