//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int CartId { get; set; }
        public Nullable<decimal> CartTotal { get; set; }
        public string CartStatus { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
