//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public VehicleModel()
        {
            this.Spares = new HashSet<Spare>();
        }
    
        public int ModelId { get; set; }
        public string TransmissionType { get; set; }
        public Nullable<System.DateTime> YearOfManufacture { get; set; }
        public string ModelName { get; set; }
        public string FuelType { get; set; }
        public string CountryMade { get; set; }
        public string AdminUsername { get; set; }
        public Nullable<int> VehicleBrand { get; set; }
        public string Username { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual VehicleBrand VehicleBrand1 { get; set; }
        public virtual ICollection<Spare> Spares { get; set; }
    }
}
