//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHubServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBrand
    {
        public VehicleBrand()
        {
            this.VehicleModels = new HashSet<VehicleModel>();
        }
    
        public int VehicleBrandId { get; set; }
        public string AdminUsername { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
    }
}
